### ISSUE TITLE
In the global menu do not appear assemblies, processes and other iniciatives created

### ISSUE THREAD

**Issue by jvicens** [NoOPeEKS/decidim-tutorial#3]
Una vegada creades les diferents assemblees, esperariem que al menu global apareixes la secció del menú, però surt en blanc:

<img width="1281" alt="Screenshot 2024-04-22 at 09 53 32" src="https://github.com/NoOPeEKS/decidim-tutorial/assets/5405396/f9905b31-3f6b-4294-b1bc-21854a435345">

En canvi en el menú per tablets/mòbil si que surten les seccions que tenen contingut:

<img width="772" alt="Screenshot 2024-04-22 at 09 54 16" src="https://github.com/NoOPeEKS/decidim-tutorial/assets/5405396/b3c9ccc3-11cd-4f8e-8c28-28ae7b487688">

**Comment by NoOPeEKS** [comment]
Hi, @jvicens your issue is most likely to be a bug with the navbar not refreshing to show the changes made. Try this workaround to force it to refresh its contents:
1. Go to admin panel -> configuration
2. Go to appearence
3. Add something to the banner and update changes.
4. Refresh main page and you should see the navbar working.
5. Delete your changes to the banner or update it with something meaningful. Your application should work normally as of now.
